# Generated by Django 4.0.4 on 2022-04-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PravdaSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20, verbose_name='Time')),
                ('title', models.CharField(max_length=455, verbose_name='Title')),
                ('link', models.CharField(max_length=455, verbose_name='Link')),
            ],
        ),
    ]
