# Generated by Django 4.0.4 on 2022-04-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NVSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=20, verbose_name='Time')),
                ('title', models.CharField(max_length=455, verbose_name='Title')),
                ('link', models.CharField(max_length=455, verbose_name='Link')),
            ],
        ),
    ]
